export const ADD_INGREDIENT = "ADD_INGREDIENT"
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT"
export const START_FETCHING_INGREDIENTS = "START_FETCHING_INGREDIENTS"
export const FETCHING_INGREDIENTS_SUCCESSED = "FETCHING_INGREDIENTS_SUCCESSED"
export const FETCHING_INGREDIENTS_FAILED = "FETCHING_INGREDIENTS_FAILED"

export const PURCHASE_ORDER_START = 'PURCHASE_ORDER_START'
export const PURCHASE_ORDER_SUCCESS = 'PURCHASE_ORDER_SUCCESS'
export const PURCHASE_ORDER_FAIL = 'PURCHASE_ORDER_FAIL'
export const INIT_PURCHASE_ORDER = 'INIT_PURCHASE_ORDER'

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const LOGOUT = 'LOGOUT'